const questionsBank = [
  // Hewan
  {indo: "kucing", eng: "cat"},
  {indo: "anjing", eng: "dog"},
  {indo: "burung", eng: "bird"},
  {indo: "ikan", eng: "fish"},
  {indo: "gajah", eng: "elephant"},
  {indo: "singa", eng: "lion"},
  {indo: "macan", eng: "tiger"},
  {indo: "ular", eng: "snake"},
  {indo: "semut", eng: "ant"},
  {indo: "lebah", eng: "bee"},
  {indo: "kupu-kupu", eng: "butterfly"},
  {indo: "kuda", eng: "horse"},
  {indo: "sapi", eng: "cow"},
  {indo: "kambing", eng: "goat"},
  {indo: "ayam", eng: "chicken"},
  {indo: "bebek", eng: "duck"},
  {indo: "elang", eng: "eagle"},
  {indo: "ikan paus", eng: "whale"},
  {indo: "lumba-lumba", eng: "dolphin"},
  {indo: "katak", eng: "frog"},

  // Warna
  {indo: "merah", eng: "red"},
  {indo: "biru", eng: "blue"},
  {indo: "kuning", eng: "yellow"},
  {indo: "hijau", eng: "green"},
  {indo: "hitam", eng: "black"},
  {indo: "putih", eng: "white"},
  {indo: "abu-abu", eng: "gray"},
  {indo: "cokelat", eng: "brown"},
  {indo: "jingga", eng: "orange"},
  {indo: "ungu", eng: "purple"},

  // Angka
  {indo: "satu", eng: "one"},
  {indo: "dua", eng: "two"},
  {indo: "tiga", eng: "three"},
  {indo: "empat", eng: "four"},
  {indo: "lima", eng: "five"},
  {indo: "enam", eng: "six"},
  {indo: "tujuh", eng: "seven"},
  {indo: "delapan", eng: "eight"},
  {indo: "sembilan", eng: "nine"},
  {indo: "sepuluh", eng: "ten"},

  // Benda sehari-hari
  {indo: "meja", eng: "table"},
  {indo: "kursi", eng: "chair"},
  {indo: "pintu", eng: "door"},
  {indo: "jendela", eng: "window"},
  {indo: "buku", eng: "book"},
  {indo: "pena", eng: "pen"},
  {indo: "pensil", eng: "pencil"},
  {indo: "kertas", eng: "paper"},
  {indo: "tas", eng: "bag"},
  {indo: "sepatu", eng: "shoes"},

  // Makanan
  {indo: "nasi", eng: "rice"},
  {indo: "roti", eng: "bread"},
  {indo: "susu", eng: "milk"},
  {indo: "keju", eng: "cheese"},
  {indo: "apel", eng: "apple"},
  {indo: "pisang", eng: "banana"},
  {indo: "jeruk", eng: "orange"},
  {indo: "mangga", eng: "mango"},
  {indo: "daging", eng: "meat"},
  {indo: "ikan", eng: "fish"},

  // Keluarga
  {indo: "ayah", eng: "father"},
  {indo: "ibu", eng: "mother"},
  {indo: "kakak", eng: "sibling"},
  {indo: "adik", eng: "younger sibling"},
  {indo: "kakek", eng: "grandfather"},
  {indo: "nenek", eng: "grandmother"},
  {indo: "paman", eng: "uncle"},
  {indo: "bibi", eng: "aunt"},
  {indo: "anak", eng: "child"},
  {indo: "bayi", eng: "baby"},

  // Sekolah
  {indo: "guru", eng: "teacher"},
  {indo: "murid", eng: "student"},
  {indo: "kelas", eng: "class"},
  {indo: "sekolah", eng: "school"},
  {indo: "pelajaran", eng: "lesson"},
  {indo: "tugas", eng: "homework"},
  {indo: "ujian", eng: "exam"},
  {indo: "perpustakaan", eng: "library"},
  {indo: "kantin", eng: "canteen"},
  {indo: "lapangan", eng: "field"},
  
  // 👉 dst sampai 400+ kata
];
